airports/urls.py
# Load path from django.urls

from django.urls import path
# Load this applications views.py file
from . import views

# Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('/', views.index),
    # Show Airport info
    # Example url /airports/MYR
    # NOTICE: the airport_code parameter in the url matches
    #      the parameter in the airport_info function
    path('/<str:airport_code>', views.airport_info),
]

csci409/urls.py
from django.contrib import admin
from django.urls import include, path

import airports.views
import flights.views
import routes.views
import tickets.views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('airports', include('airports.urls')),
    path('flights/search', include('flights.urls')),
    path('routes/search', include('routes.urls')),
    path('tickets', include('tickets.urls')),
]

flights/urls.py
from django.urls import path
# Load this applications views.py file
from . import views

# Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('/', views.index),
    # Show Airport info
    # Example url /airports/MYR
    # NOTICE: the airport_code parameter in the url matches
    #      the parameter in the airport_info function
    path('/<str:origin>/<str:destination>', views.flight_search),

]

routes/urls.py
from django.urls import path
# Load this applications views.py file
from . import views

# Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('/', views.index),
    # Show Airport info
    # Example url /airports/MYR
    # NOTICE: the airport_code parameter in the url matches
    #      the parameter in the airport_info function
    path('/<str:origin>/<str:destination>', views.route_search),
]

tickets/urls.py
from django.urls import path
# Load this applications views.py file
from . import views

# Define url patterns
urlpatterns = [
    # Get index view
    # Example url: /airports/
    path('/', views.index),
    # Show Airport info
    # Example url /airports/MYR
    # NOTICE: the airport_code parameter in the url matches
    #      the parameter in the airport_info function
    path('/<str:confirmation_number>', views.ticket_search),

]

airports/models.py
from django.db import models

# Create your models here.
class Airport(models.Model):
    name = models.CharField(max_length=225)
    airport_code = models.CharField(max_length=3)
    address = models.CharField(max_length=225)
    city = models.CharField(max_length=225)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)
    is_open = models.BooleanField()

class Runway(models.Model):
    # Runway Designation
    LEFT = 'L'
    CENTER = 'C'
    RIGHT = 'R'
    NONE = 'N'
    RUNWAY_DESIGNATION_CHOICES = [
        (LEFT, 'Left'),
        (CENTER, 'Center'),
        (RIGHT, 'Right'),
        (NONE, 'None'),
    ]
    runway_number = models.IntegerField()
    runway_designation = models.CharField(
        max_length=1,
        choices=RUNWAY_DESIGNATION_CHOICES,
        default=NONE
    )
    length = models.IntegerField()
    width = models.IntegerField()
    airport = models.ForeignKey(Airport, on_delete=models.CASCADE)

flights/models.py
from django.db import models
from airports.models import Airport


# Create your models here.
class Airline(models.Model):
    airline_name = models.CharField(max_length=200)
    airline_code = models.CharField(max_length=2)

class Flight(models.Model):
    origin = destination = models.ForeignKey(Airport, on_delete=models.PROTECT, related_name="flight_origin")
    destination = models.ForeignKey(Airport, on_delete=models.PROTECT, related_name="flight_destination")
    departure = models.DateTimeField()
    arrival = models.DateTimeField()
    aircraft_type = models.CharField(max_length=10)
    flight_number = models.IntegerField()
    airline = models.ForeignKey(Airline, on_delete=models.CASCADE)

routes/models.py
from django.db import models

# Create your models here.

tickets/models.py
from django.db import models
from airports.models import Airport
from flights.models import Flight


# Create your models here.
class Reservation(models.Model):
    flight = models.ForeignKey(Flight, on_delete=models.PROTECT)
    num_people = models.IntegerField()
    total_cost = models.DecimalField(max_digits=10, decimal_places=2)

class Ticket(models.Model):
    # Ticket Class
    FIRST = 'F'
    BUSINESS = 'B'
    MAIN = 'M'
    TICKET_CLASS_CHOICES = [
        (FIRST, 'First Class'),
        (BUSINESS, 'Business Class'),
        (MAIN, 'Main Cabin'),
    ]
    reservation = models.ForeignKey(Reservation, on_delete=models.PROTECT)
    seat = models.CharField(max_length=10)
    cost = models.DecimalField(max_digits=10, decimal_places=2)
    ticket_class = models.CharField(
        max_length=1,
        choices=TICKET_CLASS_CHOICES,
    )

airports/views.py
from django.http import HttpResponse
from django.shortcuts import render # Import the render library to make loading templates easier
from .models import Airport, Runway


def index(request):
    # Fetch all airports from database
    airports = Airport.objects.all()
    # Place all airports into a context variable for retrieval in the view.
    context = {'airports': airports}
    return render(request, 'airports/index.html', context)
    # Create a displayable string. We will change this next week.
    # This is just to show some data
    airport_list = ', '.join([a.airport_code for a in airports])
    return HttpResponse('Showing all airports: ' + airport_list);

def airport_info(request, airport_code):
    # Fetch the airport by a certain code
    # Remember as we are only expecting one airport per code we should use get
    airport = Airport.objects.get(airport_code=airport_code)
    runway = Runway.objects.filter(airport=airport)
    # Place all airports into a context variable for retrieval in the view.
    context = {'airport': airport, 'runway': runway}


    return render(request, 'airports/airport.html', context)

    # Display the airport name and code
    return HttpResponse('Showing info for airport: ' + airport.name + '- ' + airport.airport_code)

flights/views.py
from django.http import HttpResponse
from .models import Flight # Import Flight model
from airports.models import Airport # Import airport model to get airport id and code
from .models import Airline

def index(request):
    # Fetch all flights
    flights = Flight.objects.all()
    flight_list = ', '.join([f.origin.airport_code + "->" + f.destination.airport_code for f in flights])
    return HttpResponse('Listing all flights: ' + flight_list)

def flight_search(request, origin, destination):
    origin = Airport.objects.get(airport_code=origin)
    destination = Airport.objects.get(airport_code=destination)
    # Code to select flights from the database
    flights = Flight.objects.filter(origin_id=origin).filter(destination_id=destination)
    flight_list = ', '.join([f.origin.airport_code + "->" + f.destination.airport_code + " Airline Code: " +
                             f.airline.airline_code for f in flights])
    return HttpResponse('Showing flights: ' + flight_list)

routes/admin.py
from django.contrib import admin

# Register your models here.

routes/apps.py
from django.apps import AppConfig


class RoutesConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'routes'

routes/tests.py
from django.test import TestCase

# Create your tests here.

routes/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse('Hello from routes');
def route_search(request, origin, destination):
    return HttpResponse('Showing routes from: ' + origin + ' to ' + destination)

tickets/views.py
from django.http import HttpResponse
from .models import Reservation

def index(request):
    # Nothing to do here
    return HttpResponse('Hello from tickets')

def ticket_search(request, confirmation_number):
    # Select the singular reservation for the confirmation number
    # Note: the confirmation_number is the id in the Reservation table
    reservation = Reservation.objects.get(pk=confirmation_number)
    return HttpResponse('Number of tickets for confirmation number: ' + str(confirmation_number) + " is " + str(reservation.num_people))

airports/templates/airports/airport.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<!-- Q1. Inside the h1 tag display the airport_code- airport name -->
<h1>{{ airport.airport_code }}- {{ airport.name }}</h1>
<!-- Display the airport address -->
<h2>Address</h2>
<p>{{ airport.address }} {{airport.city}}, {{airport.state}} {{airport.zipcode}}</p>

<h2>Runways</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Runway</th>
            <th scope="col">Length</th>
            <th scope="col">Width</th>
        </tr>
    </thead>
    <tbody>
        <!-- Q3 Display the runway number along with designation L,C,R, etc. -->
        <!-- Runway length and width  in a table row-->
        {% for runway in airport.runway_set.all %} <!-- this is a new type of object it will fetch all of the associated runways -->
        <tr>
            <td>{{ runway.runway_number }}{{runway.runway_designation}}</td>
            <td>{{ runway.length }}</td>
            <td>{{ runway.width }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

airports/templates/airports/index.html
<!-- Specify which template to extend -->
{% extends 'base.html' %}

<!-- Add content to the content block in the main template -->
{% block content %}
<h1>Airports</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Airport Code</th>
            <th scope="col">Airport Name</th>
            <th scope="col">More Information</th>
        </tr>
    </thead>
    <tbody>
        {% for airport in airports %} <!-- Loop through airports from the context variable specified in views.py -->
            <tr>
                <td>{{ airport.airport_code }}</td>
                <td>{{ airport.name }}</td>
                <td><a href="/airports/{{ airport.airport_code }}">More Information</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">CSCI 409</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/airports">Airports</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/flights">Flights</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/tickets">Tickets</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<main>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
</body>
</html>